version: '3.7'
services:
    jupyter:
        build: .
        ports:
            - 8888:8888
        volumes:
            - .:/book
        command: bash -c 'jupyter notebook --ip=0.0.0.0 --NotebookApp.token='' /book'
